"""Amplía el catálogo con los conceptos que traen siete manuales de estadística aplicada.

Libros revisados (por su índice de capítulos, en los PDFs de «Manuales Estadística»): ALSM (solo su resumen), JW (4.ª ed.), HS,
ISLR (1.ª ed.), APM, RMS, MSDA, ESL (1.ª ed.), PSDS (3.ª ed., incompleto: solo caps. 1 y 10) y DSUS (ver LIBROS).
Añade conceptos nuevos (casi todos «huecos»: sin función en el árbol todavía), áreas nuevas y,
en conceptos que ya existían, la fuente del manual. No cambia ids ni toca nada que ya esté.

    python herramientas/ampliar_catalogo_manuales.py     # aplica a catalogo_base.json y catalogo.json
Es idempotente (se puede ejecutar varias veces).
"""
from __future__ import annotations

import json
import re
import sys
import unicodedata
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent

LIBROS = {
    "ALSM": "Applied Linear Statistical Models (Kutner, Nachtsheim, Neter, Li)",
    "JW": "Applied Multivariate Statistical Analysis (Johnson, Wichern)",
    "ISLR": "An Introduction to Statistical Learning (James, Witten, Hastie, Tibshirani)",
    "APM": "Applied Predictive Modeling (Kuhn, Johnson)",
    "PSDS": "Practical Statistics for Data Scientists (Bruce, Bruce, Gedeck)",
    "ESL": "The Elements of Statistical Learning (Hastie, Tibshirani, Friedman)",
    "DSUS": "Discovering Statistics Using IBM SPSS Statistics (Field)",
    "RMS": "Regression Modeling Strategies (Harrell)",
    "MSDA": "Mathematical Statistics and Data Analysis (Rice)",
    "HS": "Applied Multivariate Statistical Analysis (Härdle, Simar)",
}

# áreas nuevas: (id, tema, nombre, ámbito, descripción)
AREAS = [
    ("descriptiva", "t_inf", "Descriptiva y correlación", "metodologico",
     "Posición, variabilidad, gráficos, correlación, tablas de contingencia, atípicos y normalidad."),
    ("anova_disenos", "t_inf", "ANOVA y diseño de experimentos", "metodologico",
     "ANOVA de varios factores, bloques, covariables, medidas repetidas, factoriales y superficies de respuesta."),
    ("multivariante", "t_ml", "Análisis multivariante", "metodologico",
     "Normal multivariante, T² de Hotelling, factorial, canónica, discriminante y clustering clásico."),
    ("otros_modelos", "t_ml", "Otros modelos de aprendizaje", "metodologico",
     "Vecinos próximos, SVM, redes neuronales, Naive Bayes, ensamblado y alta dimensión."),
]

# (nombre, área, descripción, sinónimos, [(libro, tema)])
NUEVOS = [
    # ---------- Regresión lineal ----------
    ("Inferencia en regresión (coeficientes y predicción)", "regresion_lineal",
     "Intervalos y contrastes para los coeficientes, y diferencia entre intervalo de la media e intervalo de predicción.",
     ["t de los coeficientes", "intervalo de predicción"],
     [("ALSM", "Inferences in Regression and Correlation Analysis"), ("PSDS", "Prediction Using Regression")]),
    ("Mínimos cuadrados y enfoque matricial", "regresion_lineal",
     "Estimador (X'X)⁻¹X'y, matriz sombrero y la regresión escrita en forma matricial.",
     ["OLS", "ecuaciones normales", "matriz sombrero"],
     [("ALSM", "Matrix Approach to Simple Linear Regression Analysis"), ("ALSM", "Multiple Regression I")]),
    ("Descomposición de la varianza, R² y R² ajustado", "regresion_lineal",
     "Reparto de la variabilidad en explicada y residual, coeficiente de determinación y su versión penalizada por número de variables.",
     ["R cuadrado", "tabla ANOVA de regresión", "SSE SSR SST"],
     [("ALSM", "Multiple Regression I"), ("ISLR", "Linear Regression")]),
    ("Sumas de cuadrados extra y contraste F parcial", "regresion_lineal",
     "Contraste de si un grupo de variables aporta algo una vez incluidas las demás.",
     ["F parcial", "extra sums of squares"],
     [("ALSM", "Multiple Regression II")]),
    ("Inferencias simultáneas (Bonferroni, Working-Hotelling)", "regresion_lineal",
     "Intervalos conjuntos para varios coeficientes o para toda la recta con confianza global controlada.",
     ["bandas de confianza", "Working-Hotelling"],
     [("ALSM", "Simultaneous Inferences and Other Topics in Regression Analysis")]),
    ("Test de falta de ajuste", "regresion_lineal",
     "Contraste de si la forma funcional lineal es adecuada cuando hay réplicas en los valores de X.",
     ["lack of fit"],
     [("ALSM", "Diagnostics and Remedial Measures")]),
    ("Heterocedasticidad y mínimos cuadrados ponderados", "regresion_lineal",
     "Varianza de los errores no constante: cómo detectarla (Breusch-Pagan, White) y corregirla con pesos o errores robustos.",
     ["WLS", "Breusch-Pagan", "errores robustos de White"],
     [("ALSM", "Diagnostics and Remedial Measures"), ("ALSM", "Building the Regression Model III: Remedial Measures"), ("PSDS", "Regression Diagnostics")]),
    ("Transformaciones de Box-Cox y Yeo-Johnson", "regresion_lineal",
     "Familia de potencias que estabiliza varianza y acerca la respuesta a la normalidad; elige la potencia por verosimilitud.",
     ["Box-Cox", "Yeo-Johnson", "transformación de potencia"],
     [("ALSM", "Diagnostics and Remedial Measures"), ("APM", "Data Pre-processing")]),
    ("Observaciones influyentes (leverage, Cook, DFFITS)", "regresion_lineal",
     "Puntos con palanca alta o que cambian mucho el ajuste al retirarlos.",
     ["distancia de Cook", "leverage", "DFBETAS", "apalancamiento"],
     [("ALSM", "Building the Regression Model II: Diagnostics"), ("PSDS", "Regression Diagnostics"), ("ISLR", "Linear Regression")]),
    ("Regresión robusta (M-estimadores y LAD)", "regresion_lineal",
     "Ajustes que pesan menos los residuos grandes: Huber, mínima desviación absoluta, regresión por cuantiles.",
     ["Huber", "LAD", "regresión cuantílica"],
     [("ALSM", "Building the Regression Model III: Remedial Measures"), ("PSDS", "Regression Diagnostics")]),
    ("Interacciones y regresión polinómica", "regresion_lineal",
     "Términos producto y potencias para modelar efectos que cambian con otra variable o son curvos.",
     ["término de interacción", "polinomio"],
     [("ALSM", "Regression Models for Quantitative and Qualitative Predictors"), ("PSDS", "Polynomial and Spline Regression"), ("ISLR", "Linear Regression")]),
    ("Autocorrelación de errores (Durbin-Watson)", "regresion_lineal",
     "Residuos correlacionados en el tiempo: contraste de Durbin-Watson y correcciones de tipo Cochrane-Orcutt.",
     ["Durbin-Watson", "Cochrane-Orcutt", "residuos autocorrelados"],
     [("ALSM", "Autocorrelation in Time Series Data")]),
    ("Regresión no lineal por mínimos cuadrados", "regresion_lineal",
     "Modelos no lineales en los parámetros, ajustados iterativamente (Gauss-Newton).",
     ["NLS", "Gauss-Newton"],
     [("ALSM", "Introduction to Nonlinear Regression and Neural Networks")]),
    ("Moderación y mediación", "regresion_lineal",
     "Cuándo el efecto de X sobre Y depende de otra variable (moderación) y cuándo pasa a través de ella (mediación).",
     ["moderator", "mediator", "efecto indirecto"],
     [("DSUS", "Moderation, mediation and more regression")]),
    # ---------- GLM categórico ----------
    ("Modelos loglineales para tablas de contingencia", "glm_categoricos",
     "Poisson sobre las celdas de una tabla para estudiar asociaciones entre varias variables categóricas.",
     ["loglinear", "tablas multidimensionales"],
     [("DSUS", "Categorical data")]),
    # ---------- Modelos avanzados ----------
    ("Modelos aditivos generalizados (GAM)", "modelos_avanzados",
     "Suma de funciones suaves de cada predictor dentro de un GLM.",
     ["GAM", "funciones suaves"],
     [("ISLR", "Moving beyond Linearity"), ("ESL", "Additive Models, Trees, and Related Methods")]),
    ("Regresión local y suavizado con núcleos", "modelos_avanzados",
     "Estimar la curva con ajustes ponderados por cercanía (LOESS, Nadaraya-Watson).",
     ["LOESS", "LOWESS", "kernel smoothing", "Nadaraya-Watson"],
     [("ESL", "Kernel Smoothing Methods"), ("ISLR", "Moving beyond Linearity")]),
    ("Regresión con splines adaptativos (MARS)", "modelos_avanzados",
     "Bisagras lineales por tramos que se eligen automáticamente, con interacciones.",
     ["MARS", "multivariate adaptive regression splines"],
     [("APM", "Nonlinear Regression Models"), ("ESL", "Additive Models, Trees, and Related Methods")]),
    # ---------- Descriptiva ----------
    ("Medidas de posición (media, mediana, media truncada)", "descriptiva",
     "Resúmenes del centro de los datos y su sensibilidad a los valores extremos.",
     ["estimadores de localización", "media recortada"],
     [("PSDS", "Exploratory Data Analysis")]),
    ("Medidas de variabilidad (desviación, MAD, rango intercuartílico)", "descriptiva",
     "Resúmenes de dispersión, incluidos los robustos.",
     ["desviación típica", "IQR", "MAD", "varianza muestral"],
     [("PSDS", "Exploratory Data Analysis"), ("DSUS", "Everything you never wanted to know about statistics")]),
    ("Percentiles y diagramas de caja", "descriptiva",
     "Cuantiles de la distribución y su representación en cajas y bigotes.",
     ["boxplot", "cuantiles", "cuartiles"],
     [("PSDS", "Exploratory Data Analysis"), ("DSUS", "Exploring data with graphs")]),
    ("Histogramas y estimación de densidad", "descriptiva",
     "Formas de ver la distribución de una variable: barras, densidad por núcleos y su ancho de banda.",
     ["density plot", "KDE", "ancho de banda"],
     [("PSDS", "Exploratory Data Analysis"), ("DSUS", "Exploring data with graphs")]),
    ("Asimetría y curtosis", "descriptiva",
     "Momentos de tercer y cuarto orden: cuánto se desvía una distribución de la simetría y de colas normales.",
     ["skewness", "kurtosis"],
     [("DSUS", "The beast of bias")]),
    ("Correlación (Pearson, Spearman, Kendall)", "descriptiva",
     "Medidas de asociación lineal y de rangos entre dos variables, con su contraste.",
     ["coeficiente de correlación", "rho de Spearman", "tau de Kendall"],
     [("DSUS", "Correlation"), ("PSDS", "Exploratory Data Analysis")]),
    ("Correlación parcial y semiparcial", "descriptiva",
     "Asociación entre dos variables quitando el efecto de una tercera (o solo de una de ellas).",
     ["partial correlation"],
     [("DSUS", "Correlation")]),
    ("Tablas de contingencia y datos categóricos", "descriptiva",
     "Frecuencias cruzadas, porcentajes por fila y columna y primeras señales de asociación.",
     ["crosstab", "tabla cruzada"],
     [("PSDS", "Exploratory Data Analysis"), ("DSUS", "Categorical data")]),
    ("Valores atípicos (outliers)", "descriptiva",
     "Detectarlos (reglas de cuartiles, z robusta) y decidir si corregir, mantener o modelarlos aparte.",
     ["outliers", "anomalías"],
     [("DSUS", "The beast of bias"), ("PSDS", "Regression Diagnostics"), ("APM", "Data Pre-processing")]),
    ("Normalidad y gráficos Q-Q", "descriptiva",
     "Cómo comprobar normalidad: gráfico cuantil-cuantil y contrastes como Shapiro-Wilk o Kolmogorov-Smirnov.",
     ["QQ plot", "Shapiro-Wilk", "Kolmogorov-Smirnov", "bondad de ajuste"],
     [("DSUS", "The beast of bias"), ("PSDS", "Data and Sampling Distributions"), ("JW", "The Multivariate Normal Distribution")]),
    ("Supuestos de los modelos y sesgo", "descriptiva",
     "Normalidad, linealidad, homogeneidad de varianzas e independencia: qué se rompe cuando fallan y qué hacer.",
     ["assumptions", "sesgo de los estimadores"],
     [("DSUS", "The beast of bias"), ("ALSM", "ANOVA Diagnostics and Remedial Measures")]),
    ("Homogeneidad de varianzas (Levene, Bartlett)", "descriptiva",
     "Contrastes de igualdad de varianzas entre grupos antes de comparar medias.",
     ["Levene", "Bartlett", "Brown-Forsythe", "homocedasticidad"],
     [("DSUS", "The beast of bias"), ("ALSM", "ANOVA Diagnostics and Remedial Measures")]),
    # ---------- Fundamentos de inferencia ----------
    ("Muestreo aleatorio y sesgo de selección", "inf_fundamentos",
     "Cómo se obtiene la muestra y qué sesgos aparecen cuando no es representativa.",
     ["sample bias", "muestreo estratificado"],
     [("PSDS", "Data and Sampling Distributions")]),
    ("Regresión a la media", "inf_fundamentos",
     "Los valores extremos tienden a ser menos extremos en la medición siguiente, sin que haya efecto real.",
     ["regression to the mean"],
     [("PSDS", "Data and Sampling Distributions")]),
    ("Distribución muestral y error estándar", "inf_fundamentos",
     "Cómo varía un estadístico de muestra en muestra y su desviación típica (error estándar).",
     ["sampling distribution", "standard error"],
     [("PSDS", "Data and Sampling Distributions"), ("DSUS", "Everything you never wanted to know about statistics")]),
    ("Grados de libertad", "inf_fundamentos",
     "Cuántos valores quedan libres tras estimar parámetros; condicionan t, chi-cuadrado y F.",
     ["degrees of freedom"],
     [("PSDS", "Statistical Experiments and Significance Testing"), ("DSUS", "Everything you never wanted to know about statistics")]),
    # ---------- Contrastes ----------
    ("Test t para muestras relacionadas", "contrastes_tests",
     "Comparación de dos medias medidas sobre los mismos sujetos (diferencias por pares).",
     ["paired t-test", "t pareado"],
     [("DSUS", "Comparing two means")]),
    ("Wilcoxon de rangos con signo y Friedman", "contrastes_tests",
     "Alternativas no paramétricas para datos pareados o medidas repetidas.",
     ["Wilcoxon signed-rank", "Friedman"],
     [("DSUS", "Non-parametric models"), ("DSUS", "Repeated-measures designs")]),
    ("Test de permutación", "contrastes_tests",
     "Contraste sin distribución teórica: se reasignan las etiquetas muchas veces y se compara con el valor observado.",
     ["permutation test", "test exacto aleatorizado"],
     [("PSDS", "Statistical Experiments and Significance Testing")]),
    ("Corrección de Bonferroni y control del FWER", "contrastes_base",
     "Control de la probabilidad de algún falso positivo entre muchos contrastes (Bonferroni, Holm).",
     ["FWER", "Holm", "Bonferroni"],
     [("PSDS", "Statistical Experiments and Significance Testing"), ("ALSM", "Simultaneous Inferences and Other Topics in Regression Analysis"), ("ISLR", "Multiple Testing")]),
    # ---------- ANOVA y diseños ----------
    ("ANOVA de dos factores e interacción", "anova_disenos",
     "Efectos principales de dos factores y de su interacción, con muestras iguales.",
     ["two-way ANOVA", "ANOVA factorial"],
     [("ALSM", "Two-Factor Studies with Equal Sample Sizes"), ("DSUS", "Factorial ANOVA")]),
    ("Diseños de bloques aleatorizados", "anova_disenos",
     "Se agrupan las unidades en bloques homogéneos para quitar su variabilidad del error.",
     ["RCBD", "randomized block design"],
     [("ALSM", "Randomized Complete Block Designs")]),
    ("Análisis de la covarianza (ANCOVA)", "anova_disenos",
     "Comparar grupos ajustando por una covariable continua.",
     ["ANCOVA"],
     [("ALSM", "Analysis of Covariance"), ("DSUS", "Analysis of covariance, ANCOVA")]),
    ("Contrastes planificados y post hoc", "anova_disenos",
     "Comparaciones concretas entre medias de nivel, planeadas antes o decididas después, con su corrección.",
     ["Scheffé", "contrastes ortogonales", "post hoc"],
     [("ALSM", "Analysis of Factor Level Means"), ("DSUS", "Comparing several means: ANOVA")]),
    ("Efectos fijos y aleatorios en ANOVA", "anova_disenos",
     "Cuando los niveles son una muestra de una población de niveles: componentes de varianza y modelos mixtos.",
     ["random effects ANOVA", "componentes de la varianza"],
     [("ALSM", "Random and Mixed Effects Models")]),
    ("Diseños anidados y submuestreo", "anova_disenos",
     "Factores cuyos niveles solo tienen sentido dentro de otro factor.",
     ["nested design"],
     [("ALSM", "Nested Designs, Subsampling, and Partially Nested Designs")]),
    ("ANOVA de medidas repetidas", "anova_disenos",
     "Mismos sujetos en varias condiciones: esfericidad y corrección de Greenhouse-Geisser.",
     ["repeated measures ANOVA", "esfericidad", "Greenhouse-Geisser"],
     [("ALSM", "Repeated Measures and Related Designs"), ("DSUS", "Repeated-measures designs")]),
    ("ANOVA de diseño mixto", "anova_disenos",
     "Combina un factor entre sujetos con otro de medidas repetidas.",
     ["mixed design ANOVA", "split-plot"],
     [("DSUS", "Mixed design ANOVA")]),
    ("Análisis multivariante de la varianza (MANOVA)", "anova_disenos",
     "Compara grupos en varias variables respuesta a la vez (Wilks, Pillai).",
     ["MANOVA", "Wilks lambda", "traza de Pillai"],
     [("JW", "Comparisons of Several Multivariate Means"), ("DSUS", "Multivariate analysis of variance (MANOVA)")]),
    ("Diseños factoriales 2^k y fraccionados", "anova_disenos",
     "Exploración eficiente de muchos factores con dos niveles cada uno, completos o fracciones.",
     ["2^k", "fractional factorial"],
     [("ALSM", "Exploratory Experiments: Two-Level Factorial and Fractional Factorial Designs")]),
    ("Cuadrados latinos y bloques incompletos", "anova_disenos",
     "Diseños que controlan dos fuentes de variabilidad o bloques que no contienen todos los tratamientos.",
     ["Latin square", "BIBD"],
     [("ALSM", "Balanced Incomplete Block, Latin Square, and Related Designs")]),
    ("Metodología de superficie de respuesta", "anova_disenos",
     "Ajustar superficies cuadráticas para buscar el óptimo de un proceso.",
     ["response surface", "RSM"],
     [("ALSM", "Response Surface Methodology")]),
    ("Diagnóstico y remedios del ANOVA", "anova_disenos",
     "Comprobar los supuestos del ANOVA y transformar o cambiar de método si fallan.",
     ["supuestos ANOVA"],
     [("ALSM", "ANOVA Diagnostics and Remedial Measures")]),
    # ---------- Diseño y causalidad ----------
    ("Estudios experimentales y observacionales", "diseno_causal",
     "Diferencia entre asignar tratamientos y solo observarlos, y qué conclusiones permite cada uno.",
     ["experimento vs observacional"],
     [("ALSM", "Introduction to the Design of Experimental and Observational Studies")]),
    ("Bandidos multibrazo", "diseno_causal",
     "Experimentos adaptativos que reparten tráfico hacia lo que va mejor mientras se aprende.",
     ["multi-armed bandit", "Thompson sampling"],
     [("PSDS", "Statistical Experiments and Significance Testing")]),
    # ---------- Distribuciones ----------
    ("Distribución exponencial", "dist_univariantes",
     "Tiempo entre eventos de un proceso de Poisson; sin memoria.",
     ["exponential"],
     [("PSDS", "Data and Sampling Distributions")]),
    ("Distribución de Weibull", "dist_univariantes",
     "Tiempos de vida con riesgo creciente o decreciente según su forma.",
     ["Weibull"],
     [("PSDS", "Data and Sampling Distributions")]),
    ("Distribuciones chi-cuadrado y F", "dist_univariantes",
     "Distribuciones de contrastes de varianzas, bondad de ajuste y ANOVA.",
     ["chi cuadrado", "F de Snedecor"],
     [("PSDS", "Data and Sampling Distributions")]),
    # ---------- Selección y validación ----------
    ("Sesgo y varianza", "seleccion_validacion",
     "Descomposición del error de predicción: modelos rígidos fallan por sesgo, flexibles por varianza.",
     ["bias-variance tradeoff", "sobreajuste"],
     [("ISLR", "Statistical Learning"), ("ESL", "Model Assessment and Selection"), ("APM", "Over-Fitting and Model Tuning")]),
    ("Afinado de hiperparámetros", "seleccion_validacion",
     "Elegir los parámetros de un método con remuestreo: rejilla, aleatoria o bayesiana.",
     ["grid search", "tuning", "hyperparameter tuning"],
     [("APM", "Over-Fitting and Model Tuning"), ("PSDS", "Statistical Machine Learning")]),
    ("Cp de Mallows, PRESS y R² ajustado", "seleccion_validacion",
     "Criterios para comparar submodelos de regresión penalizando la complejidad.",
     ["Mallows Cp", "PRESS"],
     [("ALSM", "Building the Regression Model I: Model Selection and Validation"), ("ISLR", "Linear Model Selection and Regularization")]),
    ("Selección del mejor subconjunto", "seleccion_validacion",
     "Búsqueda exhaustiva o por pasos del subconjunto de predictores óptimo para cada tamaño.",
     ["best subset", "forward selection", "backward elimination"],
     [("ISLR", "Linear Model Selection and Regularization"), ("ALSM", "Building the Regression Model I: Model Selection and Validation")]),
    ("Regresión por componentes principales y PLS", "seleccion_validacion",
     "Regresar sobre pocas combinaciones de predictores (no supervisadas o guiadas por la respuesta).",
     ["PCR", "mínimos cuadrados parciales", "partial least squares"],
     [("ISLR", "Linear Model Selection and Regularization"), ("APM", "Linear Regression and Its Cousins"), ("ESL", "Linear Methods for Regression")]),
    ("Métricas de error en regresión (RMSE, MAE, R² predictivo)", "seleccion_validacion",
     "Cómo medir cuánto se equivoca un modelo de respuesta continua fuera de muestra.",
     ["RMSE", "MAE", "error cuadrático medio"],
     [("APM", "Measuring Performance in Regression Models")]),
    ("Eliminación recursiva de variables (RFE)", "seleccion_validacion",
     "Selección por envoltura: ajustar, descartar las menos importantes y repetir.",
     ["RFE", "selección por envoltura", "wrapper"],
     [("APM", "An Introduction to Feature Selection")]),
    # ---------- Evaluación de clasificadores ----------
    ("Curva precisión-recall", "evaluacion_clasificadores",
     "Compromiso entre precisión y exhaustividad; más informativa que la ROC con clases raras.",
     ["precision-recall", "PR-AUC"],
     [("APM", "Remedies for Severe Class Imbalance"), ("APM", "Measuring Performance in Classification Models")]),
    ("Curvas de ganancia y lift", "evaluacion_clasificadores",
     "Cuánto mejora un modelo la captura de positivos al contactar a los mejor puntuados.",
     ["lift chart", "gain chart", "decile"],
     [("APM", "Measuring Performance in Classification Models")]),
    ("Pérdida logarítmica y puntuación de Brier", "evaluacion_clasificadores",
     "Métricas que evalúan directamente las probabilidades predichas.",
     ["log-loss", "entropía cruzada", "Brier score"],
     [("APM", "Measuring Performance in Classification Models"), ("ESL", "Model Assessment and Selection")]),
    ("Remuestreo y coste en datos desbalanceados (SMOTE)", "evaluacion_clasificadores",
     "Sub/sobremuestreo, SMOTE y pesos por coste para clases raras.",
     ["SMOTE", "oversampling", "undersampling", "cost-sensitive"],
     [("APM", "Remedies for Severe Class Imbalance"), ("PSDS", "Classification")]),
    # ---------- Preprocesado ----------
    ("Imputación de valores faltantes", "preproceso",
     "Rellenar huecos con media, vecinos, modelos o imputación múltiple.",
     ["imputation", "imputación múltiple", "MICE"],
     [("APM", "Data Pre-processing"), ("ISLR", "Unsupervised Learning")]),
    ("Predictores de varianza casi nula y correlación alta", "preproceso",
     "Filtros previos: quitar variables casi constantes y redundantes.",
     ["near-zero variance", "filtro de correlación"],
     [("APM", "Data Pre-processing")]),
    ("Codificación de variables categóricas (one-hot y alta cardinalidad)", "preproceso",
     "Convertir categorías en columnas numéricas y qué hacer con muchas categorías.",
     ["one-hot", "dummy variables", "target encoding"],
     [("APM", "Data Pre-processing"), ("PSDS", "Regression and Prediction")]),
    # ---------- Árboles y ensembles ----------
    ("Bagging", "arboles_ensembles",
     "Promediar modelos entrenados con remuestras bootstrap para reducir varianza.",
     ["bootstrap aggregating"],
     [("ISLR", "Tree-Based Methods"), ("PSDS", "Statistical Machine Learning"), ("ESL", "Random Forests")]),
    ("Poda y complejidad de árboles", "arboles_ensembles",
     "Podar un árbol grande con un coste por hoja para evitar el sobreajuste.",
     ["cost-complexity pruning", "cp"],
     [("ISLR", "Tree-Based Methods"), ("APM", "Regression Trees and Rule-Based Models")]),
    ("Árboles de regresión y modelos basados en reglas", "arboles_ensembles",
     "Árboles con respuesta continua, árboles de modelos y listas de reglas.",
     ["regression tree", "Cubist", "rule-based"],
     [("APM", "Regression Trees and Rule-Based Models"), ("APM", "Classification Trees and Rule-Based Models")]),
    ("Gradient boosting y XGBoost", "arboles_ensembles",
     "Árboles pequeños añadidos en secuencia para corregir el error del anterior, con tasa de aprendizaje.",
     ["XGBoost", "LightGBM", "GBM"],
     [("ESL", "Boosting and Additive Trees"), ("PSDS", "Statistical Machine Learning"), ("APM", "Regression Trees and Rule-Based Models")]),
    ("Importancia de variables y dependencia parcial", "arboles_ensembles",
     "Interpretar modelos opacos: qué variables pesan más y cómo cambia la predicción al moverlas.",
     ["variable importance", "partial dependence", "permutation importance"],
     [("APM", "Measuring Predictor Importance"), ("PSDS", "Statistical Machine Learning"), ("ESL", "Additive Models, Trees, and Related Methods")]),
    # ---------- Otros modelos ----------
    ("Vecinos más cercanos (k-NN)", "otros_modelos",
     "Predecir con los k casos más parecidos; sensible a la escala y a la dimensión.",
     ["KNN", "k nearest neighbors"],
     [("PSDS", "Statistical Machine Learning"), ("ISLR", "Statistical Learning"), ("ESL", "Prototype Methods and Nearest-Neighbors")]),
    ("Máquinas de vectores soporte (SVM)", "otros_modelos",
     "Hiperplano de margen máximo, con núcleos para fronteras no lineales.",
     ["SVM", "kernel trick", "margen máximo"],
     [("ISLR", "Support Vector Machines"), ("ESL", "Support Vector Machines and Flexible Discriminants"), ("APM", "Nonlinear Classification Models")]),
    ("Redes neuronales y aprendizaje profundo", "otros_modelos",
     "Capas de combinaciones no lineales ajustadas por descenso de gradiente.",
     ["neural networks", "deep learning", "perceptrón multicapa"],
     [("ESL", "Neural Networks"), ("ALSM", "Introduction to Nonlinear Regression and Neural Networks"), ("APM", "Nonlinear Regression Models")]),
    ("Naive Bayes", "otros_modelos",
     "Clasificador bayesiano que supone predictores independientes dentro de cada clase.",
     ["Bayes ingenuo"],
     [("PSDS", "Classification"), ("APM", "Discriminant Analysis and Other Linear Classification Models")]),
    ("Stacking y ensamblado de modelos", "otros_modelos",
     "Combinar modelos distintos con un metamodelo o con promedios ponderados.",
     ["model stacking", "ensemble learning"],
     [("ESL", "Ensemble Learning"), ("APM", "A Summary of Grant Application Models")]),
    ("Alta dimensión (p mayor que n)", "otros_modelos",
     "Qué falla y qué funciona cuando hay más variables que observaciones.",
     ["p >> n", "curse of dimensionality", "maldición de la dimensión"],
     [("ESL", "High-Dimensional Problems: p ≫ N"), ("ISLR", "Linear Model Selection and Regularization")]),
    ("Modelos gráficos no dirigidos", "otros_modelos",
     "Estructura de dependencias condicionales entre variables (lasso gráfico).",
     ["graphical lasso", "redes de Markov"],
     [("ESL", "Undirected Graphical Models")]),
    # ---------- Multivariante ----------
    ("Vector aleatorio, medias y covarianza muestral", "multivariante",
     "Resúmenes de varias variables a la vez: vector de medias, matrices de covarianza y de correlación.",
     ["matriz de covarianzas", "random vector"],
     [("JW", "Aspects of Multivariate Analysis"), ("JW", "Sample Geometry and Random Sampling"), ("JW", "Matrix Algebra and Random Vectors")]),
    ("Distribución normal multivariante", "multivariante",
     "Generalización de la normal a varios ejes: propiedades, contornos elípticos y comprobación.",
     ["multivariate normal", "gaussiana multivariante"],
     [("JW", "The Multivariate Normal Distribution")]),
    ("Distancia de Mahalanobis", "multivariante",
     "Distancia que tiene en cuenta escalas y correlaciones; útil para atípicos multivariantes.",
     ["Mahalanobis"],
     [("JW", "Aspects of Multivariate Analysis"), ("JW", "The Multivariate Normal Distribution")]),
    ("T² de Hotelling", "multivariante",
     "Contraste sobre un vector de medias o entre dos grupos, análogo multivariante del test t.",
     ["Hotelling", "inferencia sobre un vector de medias"],
     [("JW", "Inferences about a Mean Vector"), ("JW", "Comparisons of Several Multivariate Means")]),
    ("Regresión multivariante", "multivariante",
     "Varias respuestas explicadas por los mismos predictores.",
     ["multivariate regression", "regresión de respuesta múltiple"],
     [("JW", "Multivariate Linear Regression Models")]),
    ("Análisis factorial", "multivariante",
     "Resumir muchas variables observadas con pocos factores latentes; rotaciones y puntuaciones.",
     ["factor analysis", "varimax", "factores latentes"],
     [("JW", "Factor Analysis and Inference for Structured Covariance Matrices"), ("DSUS", "Exploratory factor analysis")]),
    ("Fiabilidad de escalas (alfa de Cronbach)", "multivariante",
     "Consistencia interna de un conjunto de ítems que miden lo mismo.",
     ["Cronbach alpha", "fiabilidad"],
     [("DSUS", "Exploratory factor analysis")]),
    ("Correlación canónica", "multivariante",
     "Combinaciones lineales de dos grupos de variables con máxima correlación entre sí.",
     ["canonical correlation"],
     [("JW", "Canonical Correlation Analysis")]),
    ("Análisis discriminante (LDA y QDA)", "multivariante",
     "Clasificación por funciones lineales o cuadráticas bajo normalidad dentro de cada clase.",
     ["LDA", "QDA", "discriminante lineal de Fisher"],
     [("JW", "Discrimination and Classification"), ("ESL", "Linear Methods for Classification"), ("APM", "Discriminant Analysis and Other Linear Classification Models"), ("PSDS", "Classification")]),
    ("Clustering jerárquico", "multivariante",
     "Dendrograma por fusiones sucesivas; enlaces simple, completo, promedio y Ward.",
     ["dendrograma", "Ward", "hierarchical clustering"],
     [("JW", "Clustering, Distance Methods, and Ordination"), ("ISLR", "Unsupervised Learning"), ("PSDS", "Unsupervised Learning")]),
    ("Escalamiento multidimensional y ordenación", "multivariante",
     "Representar objetos en pocas dimensiones conservando sus distancias.",
     ["MDS", "ordination", "coordenadas principales"],
     [("JW", "Clustering, Distance Methods, and Ordination")]),
    ("Clustering basado en modelos (mezclas gaussianas)", "multivariante",
     "Grupos como componentes de una mezcla ajustada por EM, con elección de número por BIC.",
     ["Gaussian mixture", "GMM", "model-based clustering"],
     [("PSDS", "Unsupervised Learning"), ("ESL", "Unsupervised Learning")]),
]

# Fuentes nuevas para conceptos que YA existían: id existente -> [(libro, tema)]
FUENTES_EXTRA = {
    "c_regresion_lineal": [("ALSM", "Linear Regression with One Predictor Variable"), ("ALSM", "Multiple Regression I"), ("ISLR", "Linear Regression"), ("PSDS", "Regression and Prediction")],
    "c_multicolinealidad_y_vif": [("ALSM", "Multiple Regression II"), ("PSDS", "Regression and Prediction")],
    "c_predictores_categoricos_y_referencia": [("ALSM", "Regression Models for Quantitative and Qualitative Predictors"), ("PSDS", "Regression and Prediction")],
    "c_diagnostico_de_residuos": [("ALSM", "Diagnostics and Remedial Measures"), ("PSDS", "Regression Diagnostics")],
    "c_modelos_lineales_generalizados_glm": [("ALSM", "Logistic Regression, Poisson Regression, and Generalized Linear Models")],
    "c_regresion_logistica_binaria": [("ALSM", "Logistic Regression, Poisson Regression, and Generalized Linear Models"), ("ISLR", "Classification"), ("DSUS", "Logistic regression"), ("PSDS", "Classification")],
    "c_glm_de_conteo_poisson_y_binomial_negativa": [("ALSM", "Logistic Regression, Poisson Regression, and Generalized Linear Models")],
    "c_modelos_de_efectos_mixtos": [("ALSM", "Random and Mixed Effects Models"), ("DSUS", "Multilevel linear models")],
    "c_datos_longitudinales_y_medidas_repetidas": [("ALSM", "Repeated Measures and Related Designs"), ("DSUS", "Repeated-measures designs")],
    "c_splines_de_suavizado": [("ISLR", "Moving beyond Linearity"), ("ESL", "Basis Expansions and Regularization"), ("PSDS", "Regression and Prediction")],
    "c_anova_y_welch_anova": [("ALSM", "Single-Factor Studies"), ("DSUS", "Comparing several means: ANOVA"), ("PSDS", "Statistical Experiments and Significance Testing")],
    "c_comparaciones_multiples_tukey": [("ALSM", "Analysis of Factor Level Means")],
    "c_test_t_y_test_t_de_welch": [("DSUS", "Comparing two means"), ("PSDS", "Statistical Experiments and Significance Testing")],
    "c_tests_no_parametricos_mann_whitney_kruskal_wallis": [("DSUS", "Non-parametric models")],
    "c_test_chi_cuadrado_y_fisher": [("DSUS", "Categorical data"), ("PSDS", "Statistical Experiments and Significance Testing")],
    "c_contraste_de_hipotesis": [("PSDS", "Statistical Experiments and Significance Testing")],
    "c_significacion_estadistica_y_p_valor": [("PSDS", "Statistical Experiments and Significance Testing")],
    "c_aleatorizacion_rct_y_tests_a_b": [("PSDS", "Statistical Experiments and Significance Testing"), ("ALSM", "Introduction to the Design of Experimental and Observational Studies")],
    "c_intervalos_de_confianza": [("PSDS", "Data and Sampling Distributions"), ("ALSM", "Inferences in Regression and Correlation Analysis")],
    "c_bootstrap": [("PSDS", "Data and Sampling Distributions"), ("ISLR", "Resampling Methods")],
    "c_analisis_exploratorio_de_datos": [("PSDS", "Exploratory Data Analysis"), ("DSUS", "Exploring data with graphs")],
    "c_estadistico_robusto_mediana": [("PSDS", "Exploratory Data Analysis")],
    "c_distribucion_normal": [("PSDS", "Data and Sampling Distributions")],
    "c_distribucion_t_de_student": [("PSDS", "Data and Sampling Distributions")],
    "c_distribucion_binomial": [("PSDS", "Data and Sampling Distributions")],
    "c_distribucion_de_poisson": [("PSDS", "Data and Sampling Distributions")],
    "c_validacion_cruzada": [("ISLR", "Resampling Methods"), ("ESL", "Model Assessment and Selection"), ("APM", "Over-Fitting and Model Tuning")],
    "c_regularizacion_ridge_lasso_y_elastic_net": [("ISLR", "Linear Model Selection and Regularization"), ("ESL", "Linear Methods for Regression"), ("PSDS", "Statistical Machine Learning"), ("APM", "Linear Regression and Its Cousins")],
    "c_seleccion_de_variables_stepwise": [("ALSM", "Building the Regression Model I: Model Selection and Validation")],
    "c_criterios_de_informacion_aic_y_bic": [("ALSM", "Building the Regression Model I: Model Selection and Validation"), ("ESL", "Model Assessment and Selection")],
    "c_particion_train_test": [("ISLR", "Resampling Methods"), ("APM", "Over-Fitting and Model Tuning")],
    "c_curva_roc_y_auc": [("ISLR", "Classification"), ("APM", "Measuring Performance in Classification Models"), ("PSDS", "Classification")],
    "c_matriz_de_confusion_y_metricas_de_clasificacion": [("APM", "Measuring Performance in Classification Models"), ("PSDS", "Classification")],
    "c_desbalanceo_de_clases": [("APM", "Remedies for Severe Class Imbalance"), ("PSDS", "Classification")],
    "c_preprocesamiento_y_transformaciones": [("APM", "Data Pre-processing")],
    "c_cribado_de_variables": [("APM", "An Introduction to Feature Selection")],
    "c_k_means": [("ISLR", "Unsupervised Learning"), ("PSDS", "Unsupervised Learning"), ("ESL", "Unsupervised Learning"), ("JW", "Clustering, Distance Methods, and Ordination")],
    "c_analisis_de_componentes_principales_pca": [("JW", "Principal Components"), ("ISLR", "Unsupervised Learning"), ("PSDS", "Unsupervised Learning"), ("ESL", "Unsupervised Learning")],
    "c_arboles_de_decision": [("ISLR", "Tree-Based Methods"), ("PSDS", "Statistical Machine Learning"), ("ESL", "Additive Models, Trees, and Related Methods")],
    "c_random_forest": [("ISLR", "Tree-Based Methods"), ("PSDS", "Statistical Machine Learning"), ("ESL", "Random Forests"), ("APM", "Regression Trees and Rule-Based Models")],
    "c_boosting": [("ISLR", "Tree-Based Methods"), ("ESL", "Boosting and Additive Trees"), ("PSDS", "Statistical Machine Learning")],
    "c_tamano_del_efecto": [("DSUS", "Everything you never wanted to know about statistics")],
    "c_error_tipo_i_y_potencia": [("DSUS", "Everything you never wanted to know about statistics")],
    "c_tamano_muestral": [("ALSM", "Single-Factor Studies")],
    "c_estimacion_por_maxima_verosimilitud": [("ESL", "Model Inference and Averaging")],
    "c_datos_faltantes_y_algoritmo_em": [("ESL", "Model Inference and Averaging"), ("APM", "Data Pre-processing")],
    "c_calibracion_y_hosmer_lemeshow": [("APM", "Measuring Performance in Classification Models")],
    "c_umbral_de_decision_youden_ctable": [("APM", "Measuring Performance in Classification Models")],
    "c_estadistica_bayesiana": [("ESL", "Model Inference and Averaging")],
}


# =====================================================================================================
# Segunda pasada (con los PDFs reales): Harrell, Rice, Härdle, APM/ESL/JW en detalle y PSDS 3.ª ed. cap. 10
# =====================================================================================================
AREAS2 = [
    ("muestreo_encuestas", "t_sim", "Muestreo en encuestas", "metodologico",
     "Muestreo aleatorio simple, estimador de razón y muestreo estratificado."),
    ("ia_generativa", "t_ml", "IA generativa y LLM", "metodologico",
     "Modelos de lenguaje, alineamiento, ajuste fino, recuperación aumentada y agentes."),
]

NUEVOS2 = [
    # ---------- Probabilidad (Rice) ----------
    ("Probabilidad condicionada e independencia", "prob_fundamentos",
     "Probabilidad de un suceso dado otro, regla del producto, ley de la probabilidad total e independencia entre sucesos.",
     ["probabilidad total", "independencia de sucesos"],
     [("MSDA", "Probability")]),
    ("Distribuciones conjuntas, marginales y condicionadas", "prob_fundamentos",
     "Comportamiento conjunto de dos o más variables aleatorias y cómo se obtienen las distribuciones marginal y condicionada.",
     ["joint distribution", "marginal", "distribución condicionada"],
     [("MSDA", "Joint Distributions")]),
    ("Covarianza y correlación entre variables aleatorias", "prob_fundamentos",
     "Medidas de variación conjunta teóricas, a distinguir de sus versiones muestrales.",
     ["covarianza poblacional"],
     [("MSDA", "Expected Values")]),
    ("Función generadora de momentos", "prob_fundamentos",
     "Transformada que caracteriza una distribución y facilita sumas de variables independientes y límites.",
     ["MGF", "funcion caracteristica"],
     [("MSDA", "Expected Values"), ("HS", "Multivariate Distributions")]),
    ("Ley de los grandes números", "prob_fundamentos",
     "La media muestral converge al valor esperado al crecer n (débil y fuerte).",
     ["LLN"],
     [("MSDA", "Limit Theorems")]),
    ("Transformaciones de variables aleatorias y estadísticos de orden", "prob_fundamentos",
     "Distribución de una función de una o varias variables, y del mínimo, máximo y cuantiles muestrales.",
     ["order statistics", "cambio de variable"],
     [("MSDA", "Random Variables"), ("MSDA", "Joint Distributions")]),
    ("Método delta (aproximación de momentos)", "prob_fundamentos",
     "Aproximar media y varianza de una función de estimadores mediante su desarrollo de Taylor.",
     ["delta method"],
     [("MSDA", "Expected Values")]),
    # ---------- Inferencia (Rice, RMS) ----------
    ("Método de los momentos", "estimacion",
     "Estimar parámetros igualando momentos teóricos y muestrales.",
     ["method of moments"],
     [("MSDA", "Estimation of Parameters and Fitting of Probability Distributions")]),
    ("Suficiencia", "estimacion",
     "Un estadístico que resume toda la información de la muestra sobre el parámetro (factorización de Neyman).",
     ["sufficient statistic", "Rao-Blackwell"],
     [("MSDA", "Estimation of Parameters and Fitting of Probability Distributions")]),
    ("Eficiencia y cota de Cramér-Rao", "estimacion",
     "Límite inferior de la varianza de un estimador insesgado, vía información de Fisher.",
     ["Cramér-Rao", "información de Fisher", "eficiencia"],
     [("MSDA", "Estimation of Parameters and Fitting of Probability Distributions"), ("HS", "Theory of Estimation")]),
    ("Ajuste de distribuciones a datos", "estimacion",
     "Elegir y ajustar una familia paramétrica a una muestra y comprobar si encaja.",
     ["fitting distributions"],
     [("MSDA", "Estimation of Parameters and Fitting of Probability Distributions")]),
    ("Contrastes y intervalos de puntuación (score)", "estimacion",
     "Alternativa a Wald y razón de verosimilitudes basada en la derivada de la log-verosimilitud en el valor nulo.",
     ["score test", "Rao", "intervalo de Wilson"],
     [("RMS", "Overview of Maximum Likelihood Estimation")]),
    ("Estimación robusta de la covarianza (sandwich y cluster)", "estimacion",
     "Errores típicos válidos aunque el modelo de varianza esté mal especificado o haya observaciones agrupadas.",
     ["sandwich", "errores robustos", "cluster-robust", "Huber-White"],
     [("RMS", "Overview of Maximum Likelihood Estimation")]),
    ("Paradigma de Neyman-Pearson y dualidad con intervalos", "contrastes_base",
     "Hipótesis nula frente a alternativa, región crítica óptima y equivalencia entre rechazar y quedar fuera del intervalo.",
     ["lema de Neyman-Pearson", "región crítica"],
     [("MSDA", "Testing Hypotheses and Assessing Goodness of Fit")]),
    ("Bondad de ajuste en distribuciones discretas (multinomial y dispersión de Poisson)", "contrastes_base",
     "Contrastes chi-cuadrado y de razón de verosimilitudes para comprobar frecuencias esperadas y sobredispersión.",
     ["bondad de ajuste", "dispersion test"],
     [("MSDA", "Testing Hypotheses and Assessing Goodness of Fit")]),
    ("Contrastes de varios grados de libertad", "contrastes_base",
     "Contraste global de si un predictor (con varios términos) se asocia con la respuesta.",
     ["chunk test", "contraste conjunto"],
     [("RMS", "General Aspects of Fitting Regression Models")]),
    ("Función de distribución empírica", "inf_fundamentos",
     "Estimador no paramétrico de la distribución, base del bootstrap y del test de Kolmogorov-Smirnov.",
     ["ECDF", "EDF"],
     [("MSDA", "Summarizing Data")]),
    ("Test de McNemar (pares de proporciones)", "contrastes_tests",
     "Compara proporciones en datos pareados con respuesta binaria.",
     ["McNemar", "matched pairs"],
     [("MSDA", "The Analysis of Categorical Data")]),
    ("Test de tendencia de Jonckheere-Terpstra", "contrastes_tests",
     "Alternativa no paramétrica cuando los grupos tienen un orden esperado en la respuesta.",
     ["Jonckheere", "tendencia ordenada"],
     [("DSUS", "Non-parametric models")]),
    # ---------- Descriptiva ----------
    ("Gráficos bivariantes y multivariantes (hexbin, violín, coordenadas paralelas)", "descriptiva",
     "Visualizar relaciones entre dos o más variables cuando hay muchos puntos o mezcla de tipos.",
     ["hexagonal binning", "violin plot", "parallel coordinates", "pairplot"],
     [("PSDS", "Exploratory Data Analysis"), ("HS", "Comparison of Batches")]),
    ("Caras de Chernoff y curvas de Andrews", "descriptiva",
     "Representaciones multivariantes clásicas que codifican cada observación como cara o curva.",
     ["Chernoff faces", "Andrews curves"],
     [("HS", "Comparison of Batches")]),
    ("Diccionario de datos y catálogos", "descriptiva",
     "Documentar variables, tipos, unidades y origen para que el análisis sea reproducible.",
     ["data dictionary", "metadatos"],
     [("PSDS", "Exploratory Data Analysis")]),
    # ---------- Regresión lineal ----------
    ("Teorema de Gauss-Markov", "regresion_lineal",
     "Entre los estimadores lineales insesgados, MCO tiene mínima varianza (BLUE).",
     ["BLUE", "Gauss-Markov"],
     [("ALSM", "Linear Regression with One Predictor Variable"), ("MSDA", "Linear Least Squares")]),
    ("Gráficos de variable añadida", "regresion_lineal",
     "Muestran la contribución de un predictor una vez ajustados los demás.",
     ["added-variable plot", "partial regression plot", "residuos parciales"],
     [("ALSM", "Building the Regression Model II: Diagnostics"), ("PSDS", "Regression Diagnostics")]),
    ("Residuos estandarizados y estudentizados", "regresion_lineal",
     "Residuos escalados por su desviación para comparar y detectar atípicos en Y.",
     ["studentized residuals", "residuos eliminados"],
     [("ALSM", "Building the Regression Model II: Diagnostics")]),
    ("Coeficientes de determinación parcial y coeficientes estandarizados", "regresion_lineal",
     "Aporte marginal de un predictor y efectos expresados en unidades de desviación típica.",
     ["R² parcial", "coeficientes beta estandarizados"],
     [("ALSM", "Multiple Regression II"), ("RMS", "Linear Regression")]),
    ("Regresión inversa y calibración", "regresion_lineal",
     "Estimar X a partir de una Y observada con una recta ajustada de Y sobre X.",
     ["calibration inverse prediction"],
     [("ALSM", "Simultaneous Inferences and Other Topics in Regression Analysis")]),
    ("Errores de medida en los predictores", "regresion_lineal",
     "Efecto de medir X con ruido: atenuación de coeficientes y correcciones.",
     ["errors-in-variables", "atenuación"],
     [("ALSM", "Simultaneous Inferences and Other Topics in Regression Analysis"), ("APM", "Factors That Can Affect Model Performance")]),
    ("Regresión por el origen", "regresion_lineal",
     "Modelo sin término independiente: cuándo es razonable y qué cambia en R² e inferencia.",
     ["regression through the origin"],
     [("ALSM", "Simultaneous Inferences and Other Topics in Regression Analysis")]),
    ("Bootstrap e inferencia condicional en regresión", "regresion_lineal",
     "Remuestrear casos o residuos para obtener errores típicos e intervalos sin depender de la normalidad.",
     ["bootstrap de residuos", "bootstrap de casos"],
     [("MSDA", "Linear Least Squares"), ("ALSM", "Building the Regression Model III: Remedial Measures")]),
    ("Grados de libertad del modelo y tamaño muestral por predictor", "regresion_lineal",
     "Cuántos parámetros se pueden estimar con los datos disponibles sin sobreajustar.",
     ["events per variable", "EPV", "regla de 10 eventos por variable"],
     [("RMS", "Multivariable Modeling Strategies"), ("RMS", "General Aspects of Fitting Regression Models")]),
    # ---------- Modelos avanzados ----------
    ("Splines cúbicos restringidos (naturales)", "modelos_avanzados",
     "Splines lineales en las colas que modelan no linealidad con pocos grados de libertad.",
     ["restricted cubic splines", "natural splines"],
     [("RMS", "General Aspects of Fitting Regression Models"), ("ESL", "Basis Expansions and Regularization")]),
    ("Funciones escalonadas (step functions)", "modelos_avanzados",
     "Convertir un predictor continuo en tramos con efecto constante dentro de cada tramo.",
     ["piecewise constant"],
     [("ISLR", "Moving beyond Linearity")]),
    ("Projection pursuit y regresión inversa por cortes (SIR)", "modelos_avanzados",
     "Buscar proyecciones informativas de los predictores para regresión flexible o reducción de dimensión supervisada.",
     ["PPR", "sliced inverse regression"],
     [("HS", "Highly Interactive, Computationally Intensive Techniques"), ("ESL", "Neural Networks")]),
    ("Coeficiente de correlación intraclase (ICC)", "modelos_avanzados",
     "Proporción de la varianza debida a diferencias entre grupos en un modelo multinivel.",
     ["ICC", "intraclass correlation"],
     [("DSUS", "Multilevel linear models")]),
    ("Centrado de variables en modelos multinivel", "modelos_avanzados",
     "Centrar en la media global o del grupo para separar efectos entre y dentro de grupos.",
     ["grand mean centering", "group mean centering"],
     [("DSUS", "Multilevel linear models")]),
    # ---------- GLM categórico ----------
    ("Riesgo relativo y diferencia de riesgos", "glm_categoricos",
     "Medidas alternativas al odds ratio para comparar probabilidades entre grupos.",
     ["risk ratio", "RR", "risk difference"],
     [("RMS", "Binary Logistic Regression"), ("MSDA", "The Analysis of Categorical Data")]),
    ("Modelo de odds proporcionales y de razón continuada", "glm_categoricos",
     "Dos formas de modelar respuestas ordinales: acumulativa y por etapas.",
     ["proportional odds", "continuation ratio"],
     [("RMS", "Ordinal Logistic Regression")]),
    # ---------- Selección y validación ----------
    ("Validación por bootstrap y optimismo", "seleccion_validacion",
     "Estimar cuánto sobreestima el ajuste en la muestra el rendimiento futuro y corregirlo con remuestras.",
     ["optimism-corrected", "bootstrap de Efron-Gong", ".632"],
     [("RMS", "Resampling, Validating, Describing, and Simplifying the Model"), ("ESL", "Model Assessment and Selection")]),
    ("Optimismo del error de entrenamiento y grados de libertad efectivos", "seleccion_validacion",
     "Por qué el error de entrenamiento es optimista y cómo medir la complejidad de un ajuste.",
     ["effective degrees of freedom", "optimism"],
     [("ESL", "Model Assessment and Selection")]),
    ("Comparación de dos modelos", "seleccion_validacion",
     "Contrastar si un modelo ampliado mejora a otro anidado y medir la mejora (verosimilitud, AIC, ΔR²).",
     ["nested models", "modelos anidados"],
     [("RMS", "Multivariable Modeling Strategies")]),
    ("Descripción del modelo ajustado y nomogramas", "seleccion_validacion",
     "Presentar el efecto de cada predictor con gráficos de efectos, razones y nomogramas.",
     ["nomogram", "partial effects plot"],
     [("RMS", "Resampling, Validating, Describing, and Simplifying the Model")]),
    ("Simplificación del modelo completo por aproximación", "seleccion_validacion",
     "Ajustar un modelo reducido que imite las predicciones del completo para ganar interpretabilidad.",
     ["model approximation", "modelo reducido"],
     [("RMS", "Resampling, Validating, Describing, and Simplifying the Model")]),
    ("Sesgo de selección en la selección de variables", "seleccion_validacion",
     "Elegir variables mirando todos los datos y luego validar con los mismos produce rendimiento inflado.",
     ["selection bias"],
     [("APM", "An Introduction to Feature Selection"), ("RMS", "Multivariable Modeling Strategies")]),
    ("Comparación de modelos con remuestreo", "seleccion_validacion",
     "Comparar métricas por pares sobre las mismas remuestras para decidir entre modelos.",
     ["resamples", "diferencias pareadas"],
     [("APM", "Over-Fitting and Model Tuning")]),
    ("Validación cruzada dejando uno fuera (LOOCV)", "seleccion_validacion",
     "Caso extremo con k igual a n: bajo sesgo, coste alto salvo atajos en modelos lineales.",
     ["leave-one-out", "LOOCV"],
     [("ISLR", "Resampling Methods"), ("ESL", "Model Assessment and Selection")]),
    ("Métodos paramétricos y no paramétricos: flexibilidad frente a interpretabilidad", "seleccion_validacion",
     "Qué se gana y se pierde al suponer una forma para f frente a estimarla libremente.",
     ["interpretabilidad", "flexibilidad"],
     [("ISLR", "Statistical Learning"), ("ESL", "Overview of Supervised Learning")]),
    ("Clasificador de Bayes y error irreducible", "seleccion_validacion",
     "Cota teórica de error de clasificación y parte del error que ningún modelo puede quitar.",
     ["Bayes classifier", "irreducible error"],
     [("ISLR", "Statistical Learning"), ("ESL", "Overview of Supervised Learning")]),
    ("Teoría de la decisión estadística y pérdida cuadrática", "seleccion_validacion",
     "Marco que justifica la esperanza condicional como predictor óptimo bajo error cuadrático.",
     ["decision theory", "función de pérdida"],
     [("ESL", "Overview of Supervised Learning")]),
    ("Dominio de aplicabilidad de un modelo", "seleccion_validacion",
     "Detectar cuándo una predicción cae fuera de la zona de los datos de entrenamiento y no merece confianza.",
     ["applicability domain", "extrapolación"],
     [("APM", "Factors That Can Affect Model Performance")]),
    ("Error de medida en la respuesta y discretización de respuestas continuas", "seleccion_validacion",
     "Cómo el ruido en Y y el partir una respuesta continua en clases limitan el rendimiento.",
     ["type III error", "dicotomizar"],
     [("APM", "Factors That Can Affect Model Performance")]),
    # ---------- Preproceso ----------
    ("Mecanismos de datos faltantes (MCAR, MAR, MNAR)", "preproceso",
     "Por qué faltan los datos determina qué métodos sesgan y cuáles no.",
     ["missing completely at random", "missing at random"],
     [("RMS", "Missing Data"), ("APM", "Data Pre-processing")]),
    ("Imputación múltiple", "preproceso",
     "Crear varios conjuntos completos con ruido y combinar resultados (reglas de Rubin).",
     ["multiple imputation", "MICE", "reglas de Rubin"],
     [("RMS", "Missing Data"), ("ESL", "Additive Models, Trees, and Related Methods")]),
    ("Reducción de datos y agrupamiento de variables", "preproceso",
     "Resumir predictores redundantes con puntuaciones de grupo o componentes antes de modelar.",
     ["variable clustering", "data reduction"],
     [("RMS", "Multivariable Modeling Strategies"), ("RMS", "Case Study in Imputation and Data Reduction")]),
    # ---------- Evaluación / árboles / otros ----------
    ("AdaBoost y pérdida exponencial", "arboles_ensembles",
     "Boosting que reajusta pesos de observaciones mal clasificadas; equivale a una pérdida exponencial.",
     ["AdaBoost", "exponential loss"],
     [("ESL", "Boosting and Additive Trees")]),
    ("Regresión lineal de una matriz indicadora", "otros_modelos",
     "Clasificar multiclase regresando indicadores de clase; ilustra el problema del enmascaramiento.",
     ["indicator matrix", "masking"],
     [("ESL", "Linear Methods for Classification")]),
    ("Hiperplanos separadores y perceptrón", "otros_modelos",
     "Frontera lineal que separa clases: perceptrón y base del margen máximo.",
     ["perceptron", "separating hyperplane"],
     [("ESL", "Linear Methods for Classification"), ("ISLR", "Support Vector Machines")]),
    ("Centroides contraídos más cercanos", "otros_modelos",
     "Clasificador por centroides con selección de variables útil con muchas variables.",
     ["nearest shrunken centroids", "PAM"],
     [("APM", "Discriminant Analysis and Other Linear Classification Models")]),
    ("Análisis discriminante flexible y PLS-DA", "otros_modelos",
     "Extensiones del discriminante: bases no lineales y proyecciones PLS para respuestas categóricas.",
     ["FDA", "PLS-DA", "discriminante penalizado"],
     [("APM", "Nonlinear Classification Models"), ("ESL", "Support Vector Machines and Flexible Discriminants")]),
    ("Reglas de asociación (cesta de la compra)", "no_supervisado",
     "Patrones de co-ocurrencia con soporte, confianza y lift (algoritmo Apriori).",
     ["Apriori", "market basket", "soporte confianza lift"],
     [("ESL", "Unsupervised Learning")]),
    ("Mapas autoorganizados (SOM)", "no_supervisado",
     "Red que proyecta datos a una rejilla bidimensional preservando vecindad.",
     ["SOM", "self-organizing maps", "Kohonen"],
     [("ESL", "Unsupervised Learning")]),
    # ---------- Multivariante ----------
    ("Medidas de similitud y distancia", "multivariante",
     "Distancias euclídea, Manhattan, Minkowski, de Gower y coeficientes de similitud para variables mixtas.",
     ["distancia euclídea", "Gower", "Minkowski"],
     [("JW", "Aspects of Multivariate Analysis"), ("JW", "Clustering, Distance Methods and Ordination"), ("HS", "Cluster Analysis")]),
    ("Varianza generalizada", "multivariante",
     "Determinante de la matriz de covarianzas como medida global de dispersión.",
     ["generalized variance", "determinante de la covarianza"],
     [("JW", "Sample Geometry and Random Sampling"), ("HS", "Moving to Higher Dimensions")]),
    ("Descomposición espectral y SVD", "multivariante",
     "Autovalores, autovectores y valores singulares: base de PCA, correspondencias y mínimos cuadrados.",
     ["SVD", "autovalores", "singular value decomposition"],
     [("HS", "A Short Excursion into Matrix Algebra"), ("HS", "Decomposition of Data Matrices by Factors"), ("JW", "Matrix Algebra and Random Vectors")]),
    ("Distribuciones de Wishart y de Hotelling", "multivariante",
     "Distribuciones muestrales de la matriz de covarianzas y del T² bajo normalidad.",
     ["Wishart", "Hotelling distribution"],
     [("HS", "Theory of the Multinormal")]),
    ("Análisis de perfiles y curvas de crecimiento", "multivariante",
     "Comparar perfiles de medias en varias variables y su evolución en el tiempo.",
     ["profile analysis", "growth curves"],
     [("JW", "Comparisons of Several Multivariate Means")]),
    ("Gráficos de control multivariantes", "multivariante",
     "Vigilar varios indicadores a la vez con T² y componentes principales.",
     ["multivariate control chart", "Hotelling T2 chart"],
     [("JW", "Inferences about a Mean Vector"), ("JW", "Principal Components")]),
    ("Análisis de correspondencias", "multivariante",
     "Mapa de las asociaciones en una tabla de contingencia mediante descomposición de chi-cuadrado.",
     ["correspondence analysis", "CA"],
     [("JW", "Clustering, Distance Methods and Ordination"), ("HS", "Correspondence Analysis")]),
    ("Biplots", "multivariante",
     "Representación conjunta de observaciones y variables en un plano de componentes.",
     ["biplot"],
     [("JW", "Clustering, Distance Methods and Ordination")]),
    ("Análisis conjunto (conjoint)", "multivariante",
     "Estimar la utilidad de atributos de un producto a partir de preferencias ordenadas.",
     ["conjoint analysis", "utilidades parciales"],
     [("HS", "Conjoint Measurement Analysis")]),
    # ---------- Supervivencia (Harrell) ----------
    ("Censura, truncamiento y entrada tardía", "supervivencia",
     "Tipos de observación incompleta de tiempos de evento y cómo tratarlos en la verosimilitud.",
     ["delayed entry", "truncation", "censura por intervalo"],
     [("RMS", "Introduction to Survival Analysis")]),
    ("Funciones de supervivencia y de riesgo", "supervivencia",
     "Relaciones entre S(t), riesgo instantáneo h(t) y riesgo acumulado.",
     ["hazard function", "riesgo acumulado"],
     [("RMS", "Introduction to Survival Analysis")]),
    ("Modelos paramétricos de supervivencia", "supervivencia",
     "Exponencial, Weibull, log-normal y log-logística ajustadas por máxima verosimilitud.",
     ["parametric survival", "Weibull regression"],
     [("RMS", "Parametric Survival Models")]),
    ("Modelos de tiempo de fallo acelerado (AFT)", "supervivencia",
     "Los predictores multiplican el tiempo hasta el evento en lugar del riesgo.",
     ["accelerated failure time", "AFT"],
     [("RMS", "Parametric Survival Models")]),
    ("Diagnóstico de riesgos proporcionales (Schoenfeld)", "supervivencia",
     "Comprobar el supuesto del modelo de Cox con residuos y gráficos de log-log.",
     ["Schoenfeld residuals", "proportional hazards assumption"],
     [("RMS", "Cox Proportional Hazards Regression Model")]),
    ("Qué hacer cuando fallan los riesgos proporcionales", "supervivencia",
     "Estratificación, efectos dependientes del tiempo o modelos alternativos.",
     ["time-varying coefficients", "estratificación en Cox"],
     [("RMS", "Cox Proportional Hazards Regression Model")]),
    ("Eventos múltiples y riesgos competitivos", "supervivencia",
     "Varios tipos de evento que se excluyen o se repiten: incidencia acumulada y modelos de Fine-Gray.",
     ["competing risks", "Fine-Gray"],
     [("RMS", "Introduction to Survival Analysis")]),
    # ---------- Muestreo (Rice) ----------
    ("Muestreo aleatorio simple y parámetros poblacionales", "muestreo_encuestas",
     "Estimación de medias y totales con muestreo sin reemplazo y corrección por población finita.",
     ["SRS", "corrección por población finita"],
     [("MSDA", "Survey Sampling")]),
    ("Estimador de razón", "muestreo_encuestas",
     "Usar una variable auxiliar conocida para mejorar la precisión de una media o total.",
     ["ratio estimator"],
     [("MSDA", "Survey Sampling")]),
    ("Muestreo estratificado", "muestreo_encuestas",
     "Dividir la población en estratos homogéneos y muestrear en cada uno; asignación proporcional y óptima.",
     ["stratified sampling", "asignación de Neyman"],
     [("MSDA", "Survey Sampling")]),
    # ---------- IA generativa (PSDS 3.ª ed., cap. 10) ----------
    ("Modelos de lenguaje (LLM) y predicción de la siguiente palabra", "ia_generativa",
     "Cómo un modelo genera texto prediciendo el siguiente token; temperatura y creatividad.",
     ["LLM", "large language models", "temperatura", "tokens"],
     [("PSDS", "LLMs and Generative AI")]),
    ("Alineamiento: RLHF y modelos de recompensa", "ia_generativa",
     "Ajustar un modelo con preferencias humanas mediante modelo de recompensa o optimización directa.",
     ["RLHF", "reward model", "DPO"],
     [("PSDS", "LLMs and Generative AI")]),
    ("Ajuste fino, RAG e ingeniería de prompts", "ia_generativa",
     "Adaptar un modelo a un dominio con datos propios, recuperación aumentada o instrucciones mejor escritas.",
     ["fine tuning", "retrieval augmented generation", "prompt engineering"],
     [("PSDS", "LLMs and Generative AI")]),
    ("IA agéntica y razonamiento en cadena", "ia_generativa",
     "Modelos que descomponen tareas, usan herramientas y razonan paso a paso.",
     ["agentic AI", "chain-of-thought"],
     [("PSDS", "LLMs and Generative AI")]),
    ("Modelos generativos multimodales y de difusión", "ia_generativa",
     "Generación de imágenes y otros formatos a partir de texto; mezcla de expertos y paralelización.",
     ["diffusion", "multimodal", "mixture of experts"],
     [("PSDS", "LLMs and Generative AI")]),
]

FUENTES_EXTRA2 = {
    "c_estimacion_por_maxima_verosimilitud": [("MSDA", "Estimation of Parameters and Fitting of Probability Distributions"), ("RMS", "Overview of Maximum Likelihood Estimation")],
    "c_tests_de_wald_y_razon_de_verosimilitudes": [("MSDA", "Testing Hypotheses and Assessing Goodness of Fit"), ("RMS", "Overview of Maximum Likelihood Estimation")],
    "c_teorema_central_del_limite": [("MSDA", "Limit Theorems")],
    "c_esperanza_condicionada": [("MSDA", "Expected Values")],
    "c_axiomas_de_kolmogorov_y_bayes": [("MSDA", "Probability")],
    "c_variables_aleatorias_y_distribuciones": [("MSDA", "Random Variables")],
    "c_test_t_y_test_t_de_welch": [("MSDA", "Comparing Two Samples")],
    "c_anova_y_welch_anova": [("MSDA", "The Analysis of Variance")],
    "c_test_chi_cuadrado_y_fisher": [("MSDA", "The Analysis of Categorical Data")],
    "c_odds_ratio": [("MSDA", "The Analysis of Categorical Data"), ("RMS", "Binary Logistic Regression")],
    "c_regresion_logistica_binaria": [("RMS", "Binary Logistic Regression")],
    "c_regresion_ordinal": [("RMS", "Ordinal Logistic Regression")],
    "c_calibracion_y_hosmer_lemeshow": [("RMS", "Binary Logistic Regression")],
    "c_estadisticos_de_asociacion_c_somers_d_gamma_tau_a": [("RMS", "Binary Logistic Regression")],
    "c_multicolinealidad_y_vif": [("RMS", "Binary Logistic Regression")],
    "c_validacion_cruzada": [("RMS", "Resampling, Validating, Describing, and Simplifying the Model")],
    "c_bootstrap": [("RMS", "Resampling, Validating, Describing, and Simplifying the Model"), ("MSDA", "Linear Least Squares")],
    "c_regresion_lineal": [("MSDA", "Linear Least Squares")],
    "c_datos_faltantes_y_algoritmo_em": [("RMS", "Missing Data")],
    "c_modelo_de_riesgos_proporcionales_de_cox": [("RMS", "Cox Proportional Hazards Regression Model")],
    "c_analisis_de_supervivencia_y_censura": [("RMS", "Introduction to Survival Analysis")],
    "c_estimador_de_kaplan_meier": [("RMS", "Introduction to Survival Analysis")],
    "c_seleccion_de_variables_stepwise": [("RMS", "Multivariable Modeling Strategies")],
    "c_regularizacion_ridge_lasso_y_elastic_net": [("RMS", "Overview of Maximum Likelihood Estimation")],
    "c_analisis_de_componentes_principales_pca": [("HS", "Principal Components Analysis")],
    "c_k_means": [("HS", "Cluster Analysis")],
    "c_estadistico_robusto_mediana": [("MSDA", "Summarizing Data")],
    "c_analisis_exploratorio_de_datos": [("MSDA", "Summarizing Data"), ("HS", "Comparison of Batches")],
    "c_normalidad_y_graficos_q_q": [("MSDA", "Testing Hypotheses and Assessing Goodness of Fit")],
    "c_analisis_discriminante_lda_y_qda": [("HS", "Discriminant Analysis")],
    "c_analisis_factorial": [("HS", "Factor Analysis")],
    "c_correlacion_canonica": [("HS", "Canonical Correlation Analysis")],
    "c_clustering_jerarquico": [("HS", "Cluster Analysis")],
    "c_escalamiento_multidimensional_y_ordenacion": [("HS", "Multidimensional Scaling")],
    "c_t2_de_hotelling": [("HS", "Theory of the Multinormal")],
    "c_distribucion_normal_multivariante": [("HS", "Multivariate Distributions")],
    "c_modelo_de_markowitz_media_varianza": [("HS", "Applications in Finance")],
    "c_capm_beta_y_linea_del_mercado_de_valores": [("HS", "Applications in Finance")],
    "c_tasa_de_respuesta_encuestas": [("MSDA", "Survey Sampling")],
    "c_stacking_y_ensamblado_de_modelos": [("ESL", "Model Inference and Averaging")],
    "c_bagging": [("ESL", "Model Inference and Averaging")],
    "c_alta_dimension_p_mayor_que_n": [("ESL", "Overview of Supervised Learning")],
    "c_regresion_local_y_suavizado_con_nucleos": [("ESL", "Kernel Methods")],
}

# Referencias de la primera pasada que no existen con ese título en TU edición (ESL 1.ª, ISLR 1.ª): se marcan o se quitan.
RENOMBRAR_REFS = {
    "ESL · Random Forests": "ESL · Random Forests (2.ª ed.)",
    "ESL · Ensemble Learning": "ESL · Ensemble Learning (2.ª ed.)",
    "ESL · High-Dimensional Problems: p ≫ N": "ESL · High-Dimensional Problems: p ≫ N (2.ª ed.)",
    "ESL · Undirected Graphical Models": "ESL · Undirected Graphical Models (2.ª ed.)",
    "ESL · Kernel Smoothing Methods": "ESL · Kernel Methods",
    "ISLR · Multiple Testing": "ISLR · Multiple Testing (2.ª ed.)",
    "JW · Clustering, Distance Methods, and Ordination": "JW · Clustering, Distance Methods and Ordination",
}
QUITAR_REFS = {"APM · A Summary of Grant Application Models"}


def slug(nombre: str) -> str:
    s = unicodedata.normalize("NFKD", nombre).encode("ascii", "ignore").decode().lower()
    return "c_" + re.sub(r"_+", "_", re.sub(r"[^a-z0-9]+", "_", s)).strip("_")


def fuente(libro: str, tema: str) -> dict:
    return {"tipo": "manual", "ref": f"{libro} · {tema}", "base": LIBROS[libro]}


def ampliar(cat: dict) -> tuple[dict, dict]:
    """Devuelve (catálogo ampliado, resumen). No quita ni cambia nada existente salvo añadir fuentes
    (y corregir las referencias de RENOMBRAR_REFS / QUITAR_REFS de la primera pasada)."""
    ids = {k["id"] for k in cat["conceptos"]}
    areas = {a["id"] for a in cat["areas"]}
    temas = {t["id"] for t in cat.get("temas", [])}
    n_areas = n_conc = n_fuentes = 0
    for i, t, nombre, ambito, desc in AREAS + AREAS2:
        assert t in temas, f"tema inexistente: {t}"
        if i not in areas:
            cat["areas"].append({"id": i, "tema": t, "nombre": nombre, "ambito": ambito, "desc": desc}); areas.add(i); n_areas += 1
    for nombre, area, desc, sinon, fuentes in NUEVOS + NUEVOS2:
        cid = slug(nombre)
        assert area in areas, f"área inexistente para {nombre}: {area}"
        if cid in ids:
            continue
        cat["conceptos"].append({"id": cid, "nombre": nombre, "area": area, "desc": desc, "funciones": [],
                                 "sinonimos": sinon, "fuentes": [fuente(*f) for f in fuentes]})
        ids.add(cid); n_conc += 1
    por_id = {k["id"]: k for k in cat["conceptos"]}
    for k in cat["conceptos"]:                                    # correcciones de la primera pasada
        nuevas = []
        for f in k["fuentes"]:
            if f.get("tipo") == "manual":
                if f["ref"] in QUITAR_REFS:
                    n_fuentes += 1; continue
                if f["ref"] in RENOMBRAR_REFS:
                    f = dict(f, ref=RENOMBRAR_REFS[f["ref"]]); n_fuentes += 1
            nuevas.append(f)
        k["fuentes"] = nuevas
    extra = {}
    for d in (FUENTES_EXTRA, FUENTES_EXTRA2):
        for cid, fs in d.items():
            extra.setdefault(cid, []).extend(fs)
    for cid, fs in extra.items():
        assert cid in por_id, f"concepto inexistente: {cid}"
        ya = {f["ref"] for f in por_id[cid]["fuentes"]}
        for libro, tema in fs:
            f = fuente(libro, tema)
            if f["ref"] not in ya:
                por_id[cid]["fuentes"].append(f); ya.add(f["ref"]); n_fuentes += 1
    return cat, {"areas": n_areas, "conceptos": n_conc, "fuentes": n_fuentes}


def main(raiz: Path = RAIZ) -> int:
    for nombre in ("catalogo_base.json", "catalogo.json"):
        p = raiz / "conceptos" / nombre
        if not p.exists():
            continue
        cat = json.loads(p.read_text(encoding="utf-8"))
        cat, r = ampliar(cat)
        if any(r.values()):
            p.write_text(json.dumps(cat, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"{nombre}: +{r['areas']} áreas, +{r['conceptos']} conceptos, +{r['fuentes']} fuentes de manuales")
    return 0


if __name__ == "__main__":
    sys.exit(main())
