"""Rama SIMULACION: probabilidad y Monte Carlo, inferencia por simulación, estadística bayesiana (conjugadas, MCMC,
decisión, A/B y bandidos), procesos estocásticos (Markov, Poisson, colas, browniano) y muestreo de encuestas."""
from .bayes import (ab_bayesiano, accion_bayes, bayes_empirico_beta, chequeo_predictivo, diagnostico_mcmc, metropolis,
                    posterior_conjugado, simular_bandido)
from .inferencia import (coste_de_dicotomizar, comparar_estimadores, distribucion_muestral_simulada, informacion_fisher,
                         metodo_delta, metodo_momentos, simular_regresion_a_la_media)
from .montecarlo import (analizar_distribucion_conjunta, contrastes_aleatoriedad, convergencia_media_muestral,
                         distribucion_estadistico_orden, estimar_montecarlo, generador_congruencial,
                         generar_normal_multivariante, generar_por_aceptacion_rechazo, generar_por_inversion,
                         momentos_distribucion, teorema_bayes)
from .muestreo import (ajuste_no_respuesta, asignacion_estratos, estimador_razon, estimar_estratificado, estimar_mas,
                       extraer_muestra, tamano_muestra_encuesta)
from .procesos import (bonus_malus, cadena_markov, cadena_markov_continua, contraste_proceso_poisson, nacimiento_muerte,
                       paseo_aleatorio, ruina_jugador, simular_browniano, simular_cadena_markov, simular_proceso_poisson)

__all__ = [
    "ab_bayesiano",
    "accion_bayes",
    "ajuste_no_respuesta",
    "analizar_distribucion_conjunta",
    "asignacion_estratos",
    "bayes_empirico_beta",
    "bonus_malus",
    "cadena_markov",
    "cadena_markov_continua",
    "chequeo_predictivo",
    "comparar_estimadores",
    "contraste_proceso_poisson",
    "contrastes_aleatoriedad",
    "convergencia_media_muestral",
    "coste_de_dicotomizar",
    "diagnostico_mcmc",
    "distribucion_estadistico_orden",
    "distribucion_muestral_simulada",
    "estimador_razon",
    "estimar_estratificado",
    "estimar_mas",
    "estimar_montecarlo",
    "extraer_muestra",
    "generador_congruencial",
    "generar_normal_multivariante",
    "generar_por_aceptacion_rechazo",
    "generar_por_inversion",
    "informacion_fisher",
    "metodo_delta",
    "metodo_momentos",
    "metropolis",
    "momentos_distribucion",
    "nacimiento_muerte",
    "paseo_aleatorio",
    "posterior_conjugado",
    "ruina_jugador",
    "simular_bandido",
    "simular_browniano",
    "simular_cadena_markov",
    "simular_proceso_poisson",
    "simular_regresion_a_la_media",
    "tamano_muestra_encuesta",
    "teorema_bayes",
]
